const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.AdvancedRandom.Acts.ShufflePermutationTable,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.Every
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{IDs: 0},
	{Frames: 0},
	{Tiles_Yellow: 0},
	{Tiles_Pink: 0},
	{Logo: 0},
	{AdvancedRandom: 0},
	{Touch: 0},
	{Browser: 0},
	{Particles: 0},
	{Audio: 0},
	{Particles2: 0},
	{Text: 0},
	{Tween: 0},
	{Tiles: 0},
	{Flip_Speed: 0},
	{Tile_1: 0},
	{Tile_2: 0},
	{Picked_Tiles: 0},
	{Score: 0},
	{Wait_Before_Next_Try: 0},
	{Timer: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Tiles_Yellow: class extends self.ISpriteInstance {},
	Tiles_Pink: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Text: class extends self.ISpriteInstance {},
	Tiles: class extends self.ISpriteInstance {}
}